services:
    sigredis:
        build:
            context: .
            dockerfile: Dockerfile.redis
        container_name: sigredis
        restart: always
        # ports:
        #  - 7379:7379
        expose:
            - '${REDIS_PORT:-6379}'
        tty: true
    redispubsub:
        build: 
            context: .
            dockerfile: Dockerfile.node
        container_name: redispubsub
        init: true
        restart: always
        tty: true
        env_file: ${PWD}/.env
        ports:
         - 3030:3030
        expose:
            - ${APP_PORT:-3030}
            - ${API_PORT:-3031}
            - ${REDIS_HOST:-localhost}
            - ${REDIS_PORT:-6379}
        depends_on:
            - sigredis
    signginx:
        image: nginx:1.24.0
        container_name: signginx
        restart: always
        ports:
        #- '80:80'
        - '443:443'
        volumes:
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
            - ./keys/fullchain.pem:/etc/nginx/fullchain.pem:ro
            - ./keys/privkey.pem:/etc/nginx/privkey.pem:ro
        depends_on:
            - sigredis