services:
    messaging-redis:
        image: redis:7.2.4-alpine
        container_name: messaging-redis
        restart: always
        expose:
            - 6379
        tty: true
    messaging:
        image: denoland/deno:alpine-1.39.4
        container_name: messaging
        init: true
        restart: always
        tty: true
        ports:
         - 3030:3030
        expose:
            - 3030
        depends_on:
            - messaging-redis
        environment:
            # If "on" is logging, otherwise is not. In production, set it to "off".
            MESSAGING_LOGGING: ${MESSAGING_LOGGING:-on}
            # In production, change it to suit the environment.
            MESSAGING_CORS_ORIGIN: ${MESSAGING_CORS_ORIGIN:-*}
        working_dir: /app
        volumes:
        - .:/app
        entrypoint: ["deno", "run", "--allow-env", "--allow-net", "index.ts"]
